apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: ${{ values.name }}-cluster-role
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": ["sts:AssumeRole", "sts:TagSession"],
            "Effect": "Allow",
            "Principal": {"Service": "eks.amazonaws.com"}
          }
        ]
      }
    tags:
      Name: ${{ values.name }}-cluster-role
      Environment: ${{ values.environment }}
      ManagedBy: crossplane
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: ${{ values.name }}-cluster-eks-cluster-policy
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleRef:
      name: ${{ values.name }}-cluster-role
  providerConfigRef:
    name: default
