apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: crossplane-templates
  description: Crossplane infrastructure templates for Backstage
spec:
  targets:
    - ./templates/crossplane-aws-vpc/template.yaml
    - ./templates/crossplane-aws-eks/template.yaml
    - ./templates/crossplane-aws-s3/template.yaml
    - ./templates/crossplane-azure-rg/template.yaml
    - ./templates/crossplane-azure-redis/template.yaml
    - ./templates/crossplane-azure-storage/template.yaml
