apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: ${{ values.name }}-rg
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
spec:
  forProvider:
    location: ${{ values.region }}
    tags:
      Name: ${{ values.name }}-rg
      Environment: ${{ values.environment }}
      ManagedBy: crossplane
  providerConfigRef:
    name: default
