apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: ${{ values.name }}-vpc
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
spec:
  forProvider:
    region: ${{ values.region }}
    cidrBlock: ${{ values.vpcCidr }}
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: ${{ values.name }}-vpc
      Environment: ${{ values.environment }}
      ManagedBy: crossplane
  providerConfigRef:
    name: default
