apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: ${{ values.name }}-private-subnet-1
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
    type: private
spec:
  forProvider:
    region: ${{ values.region }}
    vpcIdRef:
      name: ${{ values.name }}-vpc
    cidrBlock: "${{ values.privateSubnet1Cidr }}"
    availabilityZone: "${{ values.az1 }}"
    mapPublicIpOnLaunch: false
    tags:
      Name: ${{ values.name }}-private-subnet-1
      Environment: ${{ values.environment }}
      Type: private
      ManagedBy: crossplane
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: ${{ values.name }}-private-subnet-2
  labels:
    environment: ${{ values.environment }}
    managed-by: crossplane
    type: private
spec:
  forProvider:
    region: ${{ values.region }}
    vpcIdRef:
      name: ${{ values.name }}-vpc
    cidrBlock: "${{ values.privateSubnet2Cidr }}"
    availabilityZone: "${{ values.az2 }}"
    mapPublicIpOnLaunch: false
    tags:
      Name: ${{ values.name }}-private-subnet-2
      Environment: ${{ values.environment }}
      Type: private
      ManagedBy: crossplane
  providerConfigRef:
    name: default
